/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/

diag_log "Init - executing initTPL.sqf"; // Reporting. Do NOT edit/remove

if (mod_ACE3 && !isVirtualCurator) then {
	if ( vehicle qipTPL_unit == qipTPL_unit ) then {
		[qipTPL_unit, currentWeapon qipTPL_unit, currentMuzzle qipTPL_unit] call ACE_SafeMode_fnc_lockSafety;
	};
};
