/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/

diag_log "Init - executing initAres.sqf"; // Reporting. Do NOT edit/remove

call compile preprocessFileLineNumbers ("\qipTPL\init\ares\Weather\Blizzard.sqf");
call compile preprocessFileLineNumbers ("\qipTPL\init\ares\Weather\Sandstorm.sqf");
