/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/

diag_log "Init - executing initAres.sqf"; // Reporting. Do NOT edit/remove

call compile preprocessFileLineNumbers ("\qipTPL\init\ares\XLA_Arsenal\XLA_arsenal_ALL.sqf");
call compile preprocessFileLineNumbers ("\qipTPL\init\ares\Weather\MKY.sqf");
