removeAllWeapons _this;
removeAllItems _this;
removeAllAssignedItems _this;
removeUniform _this;
removeVest _this;
removeBackpack _this;
removeHeadgear _this;
removeGoggles _this;
_this forceAddUniform "TRYK_U_B_PCUHsW5";
_this addItemToUniform "ACE_EarPlugs";
_this addItemToUniform "TRYK_U_B_Snowt";
_this addVest "TRYK_V_ArmorVest_Winter";
_this addItemToVest "ACE_HuntIR_monitor";
for "_i" from 1 to 2 do {_this addItemToVest "ACE_CableTie";};
for "_i" from 1 to 3 do {_this addItemToVest "30Rnd_65x39_caseless_mag";};
_this addBackpack "TRYK_Winter_pack";
for "_i" from 1 to 30 do {_this addItemToBackpack "ACE_quikclot";};
for "_i" from 1 to 3 do {_this addItemToBackpack "ACE_salineIV";};
for "_i" from 1 to 10 do {_this addItemToBackpack "ACE_epinephrine";};
for "_i" from 1 to 10 do {_this addItemToBackpack "ACE_morphine";};
_this addItemToBackpack "ACE_bodyBag";
_this addItemToBackpack "ACE_key_lockpick";
_this addItemToBackpack "ACE_DefusalKit";
for "_i" from 1 to 20 do {_this addItemToBackpack "Chemlight_red";};
_this addGoggles "TRYK_US_ESS_Glasses_WH";
_this addWeapon "arifle_MX_Hamr_pointer_F";
_this addPrimaryWeaponItem "acc_pointer_IR";
_this addPrimaryWeaponItem "optic_Hamr";
_this addWeapon "Binocular";
_this linkItem "ItemMap";
_this linkItem "ItemCompass";
_this linkItem "ItemWatch";
_this linkItem "ItemRadio";
_this linkItem "ItemGPS";
_this linkItem "TRYK_G_bala_wh_NV";
