/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/
diag_log "Init - executing initScripts.sqf"; // Reporting. Do NOT edit/remove

if (!mod_ACE3) then {
	[] execVM "\qipTPL\3rdPartyScripts\NRE_earplugs.sqf"; // Earplugs
};
