/****************************************************************
DO NOT EDIT THIS FILE
Configure the Lodout in config\loadout.sqf
****************************************************************/

diag_log "Init - executing initLoadout.sqf"; // Reporting. Do NOT edit/remove

private ["_unit","_unitString","_setLoadout","_defaultItems"];
_unit = player;

if (!local _unit || isDedicated) exitWith {};

if (mod_ACE3 && qipTPL_addDefaults) then { // ACE3 items added by default
	{
		_item = _x select 0;
		_quantity = _x select 1;
		_unit removeItems _item;
		for "_i" from 1 to _quantity do {_unit addItem _item;};
	} forEach qipTPL_defaultUniformItems;
};
