/****************************************************************
DO NOT EDIT THIS FILE
Configure the Lodout in config\loadout.sqf
****************************************************************/
if !(qipTPL_enabled) exitWith {};
diag_log "Init - executing initLoadout.sqf"; // Reporting. Do NOT edit/remove

private ["_unit","_unitString","_setLoadout","_defaultItems"];
_unit = player;

if (!local _unit || isDedicated) exitWith {};
if ((_unit getVariable "setLoadout")) exitWith {setLoadout = true;};

if ((str player) find (format ["(%1)", name player]) < 0) then {
	_unitName = toLower(str _unit);
	_unitStringArr = _unitName splitString "_";
	if (count _unitStringArr > 1) then {
		_unitStringId = _unitStringArr call BIS_fnc_arrayPop;
		_unitString = _unitStringArr joinString "_";
	} else {
		_unitString = _unitName;
	};

	if ((loadFile (format ["qipTPL\config\loadouts\%1.sqf", _unitString])) != "") then {
		_setLoadout = _unit execVM (format ["qipTPL\config\loadouts\%1.sqf", _unitString]);
		waitUntil {scriptDone _setLoadout};
	} else {
		if ((loadFile (format ["\qipTPL\Loadouts\%1.sqf", _unitString])) != "") then {
			_setLoadout = _unit execVM (format ["\qipTPL\Loadouts\%1.sqf", _unitString]);
			waitUntil {scriptDone _setLoadout};
		};
	};
};

if (mod_ACE3 && qipTPL_addDefaults) then { // ACE3 items added by default
	{
		_item = _x select 0;
		_quantity = _x select 1;
		_unit removeItems _item;
		for "_i" from 1 to _quantity do {_unit addItem _item;};
	} forEach qipTPL_defaultUniformItems;
};
_unit setVariable ["setLoadout", true, true];
setLoadout = true;
