/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/

diag_log "Init - executing initAres.sqf"; // Reporting. Do NOT edit/remove

#include "XLA_Arsenal\XLA_Arsenal.sqf"
["Wetter","Blizzard",{[[[],"\qipTPL\3rdPartyScripts\MKYBlizzard.sqf"],"BIS_fnc_execVM",true,false] call BIS_fnc_MP;}] call Ares_fnc_RegisterCustomModule;
