/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/

diag_log "Init - executing initTPL.sqf"; // Reporting. Do NOT edit/remove

waitUntil {(setLoadout)};
if (mod_ACE3 && !isCurator) then {
	if ( vehicle qipTPL_unit == qipTPL_unit ) then {
		[qipTPL_unit, currentWeapon qipTPL_unit, currentMuzzle qipTPL_unit] call ACE_SafeMode_fnc_lockSafety;
	};
};
if (mod_Ares) then {
	qipTPL_initAres = [] execVM "\qipTPL\init\ares\initAres.sqf";
};
