/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/
diag_log "Init - executing initAddons.sqf"; // Reporting. Do NOT edit/remove
/*
nul = [] execVM "\qipTPL\3rdPartyAddons\MKY\MKY_Sand_Snow_Init.sqf";
if (isServer && qipTPL_snowStorm) then {
	varEnableSnow = true;
	publicVariable "varEnableSnow";
};

if (isServer && qipTPL_sandStorm) then {
	varEnableSand = true;
	publicVariable "varEnableSand";
};
*/

/*
================================================================================================================================
>>>>> SNOW STORM Parameters =======================
================================================================================================================================

null = [direction_storm,duration_storm,effect_on_objects,ambient_sounds_al] execvm "AL_snowstorm\al_snow.sqf";

direction_storm		- integer, from 0 to 360, direction towards the wind blows expressed in compass degrees
duration_storm		- integer, life time of the SNOW STORM expressed in seconds
effect_on_objects	- boolean, if is true occasionally a random object will be thrown in the air
ambient_sounds_al	- seconds/number, a random number will be generated based on your input value and used to set the frequency for played ambient sounds
					- also determines interval at which snow gusts are generated
					- i recommend a value of 120 or higher
*/
if ((!isServer) && (player != player)) then {waitUntil {player == player};};
nul = [80,1800,false,300] execvm "AL_snowstorm\al_snow.sqf";