/****************************************************************
DO NOT EDIT THIS FILE
****************************************************************/
diag_log "Init - executing initAddons.sqf"; // Reporting. Do NOT edit/remove
/*
nul = [] execVM "\qipTPL\3rdPartyAddons\MKY\MKY_Sand_Snow_Init.sqf";
if (isServer && qipTPL_snowStorm) then {
	varEnableSnow = true;
	publicVariable "varEnableSnow";
};

if (isServer && qipTPL_sandStorm) then {
	varEnableSand = true;
	publicVariable "varEnableSand";
};
*/